"""
FP8 E4M3 Adder -- 5-Stage Pipeline, Parallel Precomputed Shift Bank.

User insight: instead of a variable barrel shift (which has log-depth MUX
cascades ~ 5.5 ns), precompute ALL 15 fixed shifts of s_mag2 simultaneously
in S_LOG.  Each fixed shift is pure wiring (zero logic delay).  Then in
S_ROUND, just select the needed one with a 15:1 MUX (~2 ns from sh3 FF).

Stage critical paths:
  S_DECODE : case MUX from input FFs              ~3.0 ns
  S_SUM    : 18-bit add/subtract from FFs         ~3.0 ns
  S_LOG    : fast_log2 (casez priority enc.)      ~4.5 ns  <-- bottleneck
             || parallel fixed shifts (wiring)    ~0.3 ns  (in parallel)
             || parallel rm/do_round flags         ~1.5 ns  (in parallel)
  S_ROUND  : 15:1 MUX selects from registered bank ~2.5 ns
  S_ENCODE : 3-way mux + clamp + pack             ~3.5 ns

All stages under 6.67 ns -> should close at 150 MHz.

TC cycles per test: 12  (5 pipeline + 1 idle + 5 TC overhead)
At 150 MHz: 4096*12 / 150e6 = 327.68 us
"""

def rgt(k):
    """Combinational: rm > hf for shift k, where rm = s_mag2[k-1:0], hf = 1<<(k-1)."""
    if k <= 1: return "1'b0"
    if k == 2: return "s_mag2[1] & s_mag2[0]"
    return "s_mag2[%d] & (|s_mag2[%d:0])" % (k-1, k-2)

def req(k):
    """Combinational: rm == hf for shift k."""
    if k == 0: return "1'b0"
    if k == 1: return "s_mag2[0]"
    if k == 2: return "s_mag2[1] & ~s_mag2[0]"
    return "s_mag2[%d] & (~|s_mag2[%d:0])" % (k-1, k-2)

def do_round(k):
    """Combinational: round-to-nearest-even decision for shift k."""
    if k == 0: return "1'b0"
    return "(%s) | ((%s) & s_mag2[%d])" % (rgt(k), req(k), k)

def oor(k):
    """Combinational: ba nibble == 4'hF (rounding would overflow to next exp)."""
    return "(s_mag2[%d:%d] == 4'hF)" % (k+3, k)

L = []
A = L.append

A("// " + "="*74)
A("// FP8 E4M3 Adder -- 5-Stage Pipeline with Parallel Precomputed Shift Bank")
A("// " + "="*74)
A("// S_DECODE : case-based mag decode + NaN/zero detect")
A("// S_SUM    : signed sum from registered magnitudes")
A("// S_LOG    : fast_log2 || 15 parallel fixed shifts + do_round flags")
A("//            All registered. Bottleneck = fast_log2 ~4.5 ns.")
A("// S_ROUND  : 15:1 MUX select from registered shift bank  ~2.5 ns")
A("// S_ENCODE : 3-way mux + clamp + pack -> result, done=1  ~3.5 ns")
A("//")
A("// TC cycles per test: 12   At 150 MHz: 4096*12/150e6 = 328 us")
A("// " + "="*74)
A("")
A("module fp8_adder (")
A("    input  wire       clk,")
A("    input  wire       rst_n,")
A("    input  wire       start,")
A("    input  wire [7:0] a,")
A("    input  wire [7:0] b,")
A("    output reg  [7:0] result,")
A("    output reg        done,")
A("    output reg        busy")
A(");")
A("")
A("    localparam S_IDLE   = 3'd0;")
A("    localparam S_DECODE = 3'd1;")
A("    localparam S_SUM    = 3'd2;")
A("    localparam S_LOG    = 3'd3;")
A("    localparam S_ROUND  = 3'd4;")
A("    localparam S_ENCODE = 3'd5;")
A("")
A("    reg [2:0] state;")
A("")
A("    // Stage registers -- S_DECODE outputs")
A("    reg        sv1; reg [7:0] sr1;")
A("    reg        a_neg1; reg [17:0] a_mag1;")
A("    reg        b_neg1; reg [17:0] b_mag1;")
A("")
A("    // Stage registers -- S_SUM outputs")
A("    reg        sv2; reg [7:0] sr2;")
A("    reg        s_neg2; reg [18:0] s_mag2;")
A("")
A("    // Stage registers -- S_LOG outputs (fast_log2 path)")
A("    reg        sv3; reg [7:0] sr3;")
A("    reg        s_neg3; reg [18:0] s_mag3;")
A("    reg [4:0]  sh3; reg [3:0] eb3; reg [3:0] eb3_p1;")
A("    reg        is_z3; reg is_ov3; reg is_dn3;")
A("")
A("    // Parallel shift bank -- set in S_LOG from s_mag2 (pure wiring + small logic)")
A("    // ba_arr[k]  = s_mag2[k+3:k]        (4 bits, zero logic delay = fixed bit-slice)")
A("    // bp_arr[k]  = ba_arr[k] + 1        (4-bit +1 adder, ~0.5 ns)")
A("    // oor_arr[k] = (ba_arr[k] == 4'hF)  (4-XNOR + AND, ~0.3 ns)")
A("    // dr_arr[k]  = round-to-nearest-even decision for shift k (~1.5 ns)")
A("    reg [3:0] ba_arr  [0:14];")
A("    reg [3:0] bp_arr  [0:14];")
A("    reg       oor_arr [0:14];")
A("    reg       dr_arr  [0:14];")
A("")
A("    // Stage registers -- S_ROUND outputs (15:1 MUX selects)")
A("    reg        sv4; reg [7:0] sr4;")
A("    reg        s_neg4; reg [18:0] s_mag4;")
A("    reg [3:0]  eb4; reg [3:0] eb4_p1;")
A("    reg [3:0]  ba4;       // selected ba nibble")
A("    reg [3:0]  bp4;       // selected ba+1 nibble")
A("    reg        oor4;      // selected overflow flag")
A("    reg        dr4;       // selected do_round flag")
A("    reg        is_z4; reg is_ov4; reg is_dn4;")
A("")
A("    // ---- Case-based magnitude decode (16-way MUX, ~2 ns from input FFs) ----")
A("    function [17:0] decode_mag;")
A("        input [7:0] fp;")
A("        reg [3:0] m;")
A("        begin")
A("            m = {1'b1, fp[2:0]};")
A("            case (fp[6:3])")
A("                4'd0:  decode_mag = {15'd0, fp[2:0]};")
A("                4'd1:  decode_mag = {14'd0, m};")
A("                4'd2:  decode_mag = {13'd0, m,  1'b0};")
A("                4'd3:  decode_mag = {12'd0, m,  2'd0};")
A("                4'd4:  decode_mag = {11'd0, m,  3'd0};")
A("                4'd5:  decode_mag = {10'd0, m,  4'd0};")
A("                4'd6:  decode_mag = { 9'd0, m,  5'd0};")
A("                4'd7:  decode_mag = { 8'd0, m,  6'd0};")
A("                4'd8:  decode_mag = { 7'd0, m,  7'd0};")
A("                4'd9:  decode_mag = { 6'd0, m,  8'd0};")
A("                4'd10: decode_mag = { 5'd0, m,  9'd0};")
A("                4'd11: decode_mag = { 4'd0, m, 10'd0};")
A("                4'd12: decode_mag = { 3'd0, m, 11'd0};")
A("                4'd13: decode_mag = { 2'd0, m, 12'd0};")
A("                4'd14: decode_mag = { 1'd0, m, 13'd0};")
A("                4'd15: decode_mag = {        m, 14'd0};")
A("            endcase")
A("        end")
A("    endfunction")
A("")
A("    // ---- Priority-encoder log2 (18-bit casez, ~4.5 ns) -----------------")
A("    function [4:0] fast_log2;")
A("        input [17:0] v;")
A("        begin")
A("            casez (v)")
A("                18'b1?????????????????: fast_log2 = 5'd17;")
A("                18'b01????????????????: fast_log2 = 5'd16;")
A("                18'b001???????????????: fast_log2 = 5'd15;")
A("                18'b0001??????????????: fast_log2 = 5'd14;")
A("                18'b00001?????????????: fast_log2 = 5'd13;")
A("                18'b000001????????????: fast_log2 = 5'd12;")
A("                18'b0000001???????????: fast_log2 = 5'd11;")
A("                18'b00000001??????????: fast_log2 = 5'd10;")
A("                18'b000000001?????????: fast_log2 = 5'd9;")
A("                18'b0000000001????????: fast_log2 = 5'd8;")
A("                18'b00000000001???????: fast_log2 = 5'd7;")
A("                18'b000000000001??????: fast_log2 = 5'd6;")
A("                18'b0000000000001?????: fast_log2 = 5'd5;")
A("                18'b00000000000001????: fast_log2 = 5'd4;")
A("                18'b000000000000001???: fast_log2 = 5'd3;")
A("                18'b0000000000000001??: fast_log2 = 5'd2;")
A("                18'b00000000000000001?: fast_log2 = 5'd1;")
A("                default:               fast_log2 = 5'd0;")
A("            endcase")
A("        end")
A("    endfunction")
A("")
A("    always @(posedge clk or negedge rst_n) begin")
A("        if (!rst_n) begin")
A("            state   <= S_IDLE;")
A("            sv1 <= 0; sr1 <= 0; a_neg1 <= 0; a_mag1 <= 0; b_neg1 <= 0; b_mag1 <= 0;")
A("            sv2 <= 0; sr2 <= 0; s_neg2 <= 0; s_mag2 <= 0;")
A("            sv3 <= 0; sr3 <= 0; s_neg3 <= 0; s_mag3 <= 0;")
A("            sh3 <= 0; eb3 <= 0; eb3_p1 <= 0; is_z3 <= 0; is_ov3 <= 0; is_dn3 <= 0;")
A("            sv4 <= 0; sr4 <= 0; s_neg4 <= 0; s_mag4 <= 0;")
A("            eb4 <= 0; eb4_p1 <= 0; ba4 <= 0; bp4 <= 0; oor4 <= 0; dr4 <= 0;")
A("            is_z4 <= 0; is_ov4 <= 0; is_dn4 <= 0;")
A("            result <= 0; done <= 0; busy <= 0;")
A("        end else begin")
A("            done <= 1'b0;")
A("            case (state)")
A("")
A("                // Wait for start pulse")
A("                S_IDLE: begin")
A("                    if (start) begin busy <= 1'b1; state <= S_DECODE; end")
A("                end")
A("")
A("                // ~3 ns: 16-way case MUX from input ports")
A("                S_DECODE: begin")
A("                    if (((a[6:3] == 4'hF) && (a[2:0] == 3'h7)) ||")
A("                        ((b[6:3] == 4'hF) && (b[2:0] == 3'h7)))")
A("                        begin sv1 <= 1'b1; sr1 <= 8'h7F; end")
A("                    else if ((a[6:0] == 7'd0) && (b[6:0] == 7'd0))")
A("                        begin sv1 <= 1'b1; sr1 <= (a[7] && b[7]) ? 8'h80 : 8'h00; end")
A("                    else")
A("                        begin sv1 <= 1'b0; sr1 <= 8'h00; end")
A("                    a_neg1 <= a[7]; a_mag1 <= decode_mag(a);")
A("                    b_neg1 <= b[7]; b_mag1 <= decode_mag(b);")
A("                    state  <= S_SUM;")
A("                end")
A("")
A("                // ~3 ns: 18-bit add/compare/subtract from FFs")
A("                S_SUM: begin")
A("                    sv2 <= sv1; sr2 <= sr1;")
A("                    if (a_neg1 == b_neg1) begin")
A("                        s_neg2 <= a_neg1;")
A("                        s_mag2 <= {1'b0, a_mag1} + {1'b0, b_mag1};")
A("                    end else if (a_mag1 >= b_mag1) begin")
A("                        s_neg2 <= a_neg1;")
A("                        s_mag2 <= {1'b0, a_mag1} - {1'b0, b_mag1};")
A("                    end else begin")
A("                        s_neg2 <= b_neg1;")
A("                        s_mag2 <= {1'b0, b_mag1} - {1'b0, a_mag1};")
A("                    end")
A("                    state <= S_LOG;")
A("                end")
A("")
A("                // Bottleneck ~4.5 ns (fast_log2 path).")
A("                // Parallel shift bank computed simultaneously -- each is just")
A("                // a fixed bit-slice of s_mag2 (zero logic delay = pure wiring)")
A("                // plus a small comparison/adder (~0.5-1.5 ns), all in parallel.")
A("                S_LOG: begin")
A("                    sv3    <= sv2; sr3 <= sr2;")
A("                    s_neg3 <= s_neg2; s_mag3 <= s_mag2;")
A("                    is_z3  <= (s_mag2 == 19'd0);")
A("                    is_ov3 <= (s_mag2 > 19'd229376);")
A("                    is_dn3 <= (s_mag2 != 19'd0) && (s_mag2 < 19'd8);")
A("                    begin : log_block")
A("                        reg [4:0] lg;")
A("                        lg      = fast_log2(s_mag2[17:0]);")
A("                        sh3     <= (lg >= 5'd3) ? lg - 5'd3 : 5'd0;")
A("                        eb3     <= (lg >= 5'd2) ? lg[3:0] - 4'd2 : 4'd0;")
A("                        eb3_p1  <= (lg >= 5'd1) ? lg[3:0] - 4'd1 : 4'd0;")
A("                    end")

# Parallel shift bank: for each k=0..14
for k in range(15):
    ba_lo = k
    ba_hi = k + 3
    A("                    // k=%d: ba = s_mag2[%d:%d]" % (k, ba_hi, ba_lo))
    A("                    ba_arr[%d]  <= s_mag2[%d:%d];" % (k, ba_hi, ba_lo))
    A("                    bp_arr[%d]  <= s_mag2[%d:%d] + 4'd1;" % (k, ba_hi, ba_lo))
    A("                    oor_arr[%d] <= %s;" % (k, oor(k)))
    A("                    dr_arr[%d]  <= %s;" % (k, do_round(k)))

A("                    state <= S_ROUND;")
A("                end")
A("")
A("                // ~2.5 ns: 15:1 MUX select on sh3 from registered shift bank.")
A("                // sh3 is a registered FF; each ba_arr/dr_arr element is a FF.")
A("                // Quartus synthesizes variable index as a balanced MUX tree.")
A("                S_ROUND: begin")
A("                    sv4     <= sv3; sr4 <= sr3;")
A("                    s_neg4  <= s_neg3; s_mag4 <= s_mag3;")
A("                    eb4     <= eb3; eb4_p1 <= eb3_p1;")
A("                    is_z4   <= is_z3; is_ov4 <= is_ov3; is_dn4 <= is_dn3;")
A("                    ba4     <= ba_arr[sh3];")
A("                    bp4     <= bp_arr[sh3];")
A("                    oor4    <= oor_arr[sh3];")
A("                    dr4     <= (sh3 == 5'd0) ? 1'b0 : dr_arr[sh3];")
A("                    state   <= S_ENCODE;")
A("                end")
A("")
A("                // ~3.5 ns: 3-way mux (all inputs registered) + clamp + pack")
A("                S_ENCODE: begin")
A("                    if (sv4) begin")
A("                        result <= sr4;")
A("                    end else if (is_z4) begin")
A("                        result <= 8'h00;")
A("                    end else if (is_ov4) begin")
A("                        result <= {s_neg4, 7'h7E};")
A("                    end else if (is_dn4) begin")
A("                        result <= {s_neg4, 1'b0, 3'b000, s_mag4[2:0]};")
A("                    end else begin : encode_block")
A("                        reg        real_ov;")
A("                        reg [3:0]  ba_f, eb_f;")
A("                        real_ov = dr4 && oor4;")
A("                        if (real_ov)        begin ba_f = 4'd8;    eb_f = eb4_p1; end")
A("                        else if (dr4)       begin ba_f = bp4;     eb_f = eb4;    end")
A("                        else                begin ba_f = ba4;     eb_f = eb4;    end")
A("                        if ((eb_f > 4'd15) || ((eb_f == 4'd15) && (ba_f == 4'hF)))")
A("                            result <= {s_neg4, 7'h7E};")
A("                        else")
A("                            result <= {s_neg4, eb_f[3:0], ba_f[2:0]};")
A("                    end")
A("                    done  <= 1'b1;")
A("                    busy  <= 1'b0;")
A("                    state <= S_IDLE;")
A("                end")
A("")
A("                default: state <= S_IDLE;")
A("            endcase")
A("        end")
A("    end")
A("")
A("endmodule")

verilog = "\n".join(L) + "\n"

out = r"c:\Users\Administrator\Desktop\Hackathon 2026\Our Fork\TechCrash2026\challenge_submissions\fp8_adder\fpga\src\fp8_adder.v"
with open(out, "w", encoding="utf-8") as f:
    f.write(verilog)
print("Written: %s (%d bytes)" % (out, len(verilog)))
print("Lines: %d" % len(L))
