"""
6-stage FP8 adder pipeline with prefix-OR precompute targeting 200 MHz.

Key: break the fast_log2 bottleneck by precomputing 18 prefix-OR signals
(any[k] = |s_mag2[17:k]) one stage earlier. Then log2 is encoded from 18
registered 1-bit FFs -- just 2 logic levels (~1.5 ns) instead of 18-input
casez (~4.5 ns).

Also precomputes full result bytes per shift so S_ENCODE is trivial.

Stages:
  S_DECODE  (~3.0 ns): case mag decode + NaN/zero detect
  S_SUM     (~3.0 ns): signed 19-bit add/subtract
  S_PREHASH (~2.5 ns): 18 prefix-ORs + 15 precomputed result bytes
  S_LOG     (~1.5 ns): log2 from prefix-OR FFs + one-hot sh selection
  S_ROUND   (~1.0 ns): AND-OR select of precomputed result byte
  S_ENCODE  (~0.5 ns): sign combine + special-case override

Bottleneck: S_DECODE and S_SUM at ~3 ns -> Fmax ~300+ MHz theoretically.
Realistic with routing/setup at 85degC: 200-250 MHz.

TC cycles per test: 6 pipeline stages + 1 IDLE + 5 TC overhead = 13
  At 200 MHz: 4096*13/200e6 = 266 us
  At 250 MHz: 4096*13/250e6 = 213 us (M=15,D=3  VCO=750 MHz)
"""

L = []
A = L.append

def do_round_expr(k):
    """Round-to-nearest-even for shift k, from individual s_mag2 bits.
    rm = s_mag2[k-1:0], hf = 1<<(k-1).
    rm > hf:  s_mag2[k-1] && |s_mag2[k-2:0]
    rm == hf: s_mag2[k-1] && ~|s_mag2[k-2:0]  AND ba_lsb = s_mag2[k]
    round = (rm>hf) | (rm==hf & ba_lsb)
          = s_mag2[k-1] & ( |s_mag2[k-2:0] | s_mag2[k] )
    Special k=0: no rounding bits below, no round.
    Special k=1: rm = s_mag2[0], hf=1. rm>hf: impossible (rm in {0,1}).
                 rm==hf: s_mag2[0]==1 AND ba_lsb=s_mag2[1]. round=s_mag2[0]&s_mag2[1].
    """
    if k == 0:
        return "1'b0"
    elif k == 1:
        return "(s_mag2[0] & s_mag2[1])"
    elif k == 2:
        return "(s_mag2[1] & (s_mag2[0] | s_mag2[2]))"
    else:
        lower_or = "|s_mag2[%d:0]" % (k-2)
        return "(s_mag2[%d] & (%s | s_mag2[%d]))" % (k-1, lower_or, k)

# Module header
A("// " + "="*74)
A("// FP8 E4M3 Adder -- 6-Stage Pipeline, Prefix-OR Precompute, 200 MHz target")
A("// " + "="*74)
A("// S_DECODE  : case mag decode + NaN/zero    ~3.0 ns")
A("// S_SUM     : signed 19-bit add/subtract    ~3.0 ns")
A("// S_PREHASH : 18 prefix-ORs || 15 precomputed result bytes  ~2.5 ns")
A("// S_LOG     : log2 from prefix-OR FFs + one-hot sh          ~1.5 ns")
A("// S_ROUND   : AND-OR byte select from one-hot FFs           ~1.0 ns")
A("// S_ENCODE  : sign + special-case override                   ~0.5 ns")
A("//")
A("// TC cycles/test: 13    At 200 MHz: 4096*13/200e6 = 266 us")
A("// " + "="*74)
A("")
A("module fp8_adder (")
A("    input  wire       clk,")
A("    input  wire       rst_n,")
A("    input  wire       start,")
A("    input  wire [7:0] a,")
A("    input  wire [7:0] b,")
A("    output reg  [7:0] result,")
A("    output reg        done,")
A("    output reg        busy")
A(");")
A("")
A("    localparam S_IDLE    = 3'd0;")
A("    localparam S_DECODE  = 3'd1;")
A("    localparam S_SUM     = 3'd2;")
A("    localparam S_PREHASH = 3'd3;")
A("    localparam S_LOG     = 3'd4;")
A("    localparam S_ROUND   = 3'd5;")
A("    localparam S_ENCODE  = 3'd6;")
A("")
A("    reg [2:0] state;")
A("")
A("    // --- S_DECODE stage registers ---")
A("    reg        sv1; reg [7:0] sr1;")
A("    reg        a_neg1; reg [17:0] a_mag1;")
A("    reg        b_neg1; reg [17:0] b_mag1;")
A("")
A("    // --- S_SUM stage registers ---")
A("    reg        sv2; reg [7:0] sr2;")
A("    reg        s_neg2; reg [18:0] s_mag2;")
A("")
A("    // --- S_PREHASH stage registers ---")
A("    // Prefix-OR signals: any[k] = |s_mag2[17:k]")
A("    reg [17:0] any3;      // one bit per shift position")
A("    // Precomputed result bytes for each shift k=0..14")
A("    // byte7[k] = {eb_f[3:0], ba_f[2:0]} ready to use (7 bits)")
A("    // is_clamped[k] = 1 if result should be 7'h7E instead")
A("    reg [6:0]  rbyte3 [0:14];  // result byte per shift")
A("    reg [14:0] rclamp3;        // clamp flag per shift")
A("    reg        sv3; reg [7:0] sr3;")
A("    reg        s_neg3;")
A("    reg        is_z3, is_ov3, is_dn3;")
A("    reg [18:0] s_mag3;   // carry-through for denormal")
A("")
A("    // --- S_LOG stage registers ---")
A("    reg        sv4; reg [7:0] sr4;")
A("    reg        s_neg4;")
A("    reg        is_z4, is_ov4, is_dn4;")
A("    reg [18:0] s_mag4;")
A("    // One-hot shift selector (15 bits, sh_oh[k] = 1 if sh==k)")
A("    reg [14:0] sh_oh4;")
A("    // Selected result byte and clamp flag forwarded in S_LOG")
A("    // (actually selected in S_ROUND using one-hot AND-OR)")
A("")
A("    // --- S_ROUND stage registers ---")
A("    reg        sv5; reg [7:0] sr5;")
A("    reg        s_neg5;")
A("    reg        is_z5, is_ov5, is_dn5;")
A("    reg [18:0] s_mag5;")
A("    reg [6:0]  rbyte5;    // selected result byte")
A("    reg        rclamp5;   // selected clamp flag")
A("")
A("    // ---- Case-based magnitude decode (16-way MUX, ~2 ns) ---------------")
A("    function [17:0] decode_mag;")
A("        input [7:0] fp;")
A("        reg [3:0] m;")
A("        begin")
A("            m = {1'b1, fp[2:0]};")
A("            case (fp[6:3])")
A("                4'd0:  decode_mag = {15'd0, fp[2:0]};")
A("                4'd1:  decode_mag = {14'd0, m};")
A("                4'd2:  decode_mag = {13'd0, m, 1'b0};")
A("                4'd3:  decode_mag = {12'd0, m, 2'd0};")
A("                4'd4:  decode_mag = {11'd0, m, 3'd0};")
A("                4'd5:  decode_mag = {10'd0, m, 4'd0};")
A("                4'd6:  decode_mag = { 9'd0, m, 5'd0};")
A("                4'd7:  decode_mag = { 8'd0, m, 6'd0};")
A("                4'd8:  decode_mag = { 7'd0, m, 7'd0};")
A("                4'd9:  decode_mag = { 6'd0, m, 8'd0};")
A("                4'd10: decode_mag = { 5'd0, m, 9'd0};")
A("                4'd11: decode_mag = { 4'd0, m, 10'd0};")
A("                4'd12: decode_mag = { 3'd0, m, 11'd0};")
A("                4'd13: decode_mag = { 2'd0, m, 12'd0};")
A("                4'd14: decode_mag = { 1'd0, m, 13'd0};")
A("                4'd15: decode_mag = {        m, 14'd0};")
A("            endcase")
A("        end")
A("    endfunction")
A("")
A("    integer _ri;")
A("    always @(posedge clk or negedge rst_n) begin")
A("        if (!rst_n) begin")
A("            state   <= S_IDLE;")
A("            sv1 <= 0; sr1 <= 0; a_neg1 <= 0; a_mag1 <= 0; b_neg1 <= 0; b_mag1 <= 0;")
A("            sv2 <= 0; sr2 <= 0; s_neg2 <= 0; s_mag2 <= 0;")
A("            any3 <= 0; sv3 <= 0; sr3 <= 0; s_neg3 <= 0; s_mag3 <= 0;")
A("            is_z3 <= 0; is_ov3 <= 0; is_dn3 <= 0;")
A("            rclamp3 <= 0;")
A("            for (_ri=0; _ri<15; _ri=_ri+1) rbyte3[_ri] <= 7'd0;")
A("            sv4 <= 0; sr4 <= 0; s_neg4 <= 0; s_mag4 <= 0;")
A("            is_z4 <= 0; is_ov4 <= 0; is_dn4 <= 0; sh_oh4 <= 0;")
A("            sv5 <= 0; sr5 <= 0; s_neg5 <= 0; s_mag5 <= 0;")
A("            is_z5 <= 0; is_ov5 <= 0; is_dn5 <= 0;")
A("            rbyte5 <= 0; rclamp5 <= 0;")
A("            result <= 0; done <= 0; busy <= 0;")
A("        end else begin")
A("            done <= 1'b0;")
A("            case (state)")
A("")
A("                S_IDLE: begin")
A("                    if (start) begin busy <= 1'b1; state <= S_DECODE; end")
A("                end")
A("")
A("                // ~3 ns: 16-way case MUX from input ports")
A("                S_DECODE: begin")
A("                    if (((a[6:3]==4'hF)&&(a[2:0]==3'h7)) || ((b[6:3]==4'hF)&&(b[2:0]==3'h7)))")
A("                        begin sv1<=1; sr1<=8'h7F; end")
A("                    else if ((a[6:0]==7'd0) && (b[6:0]==7'd0))")
A("                        begin sv1<=1; sr1<=(a[7]&&b[7])?8'h80:8'h00; end")
A("                    else begin sv1<=0; sr1<=8'h00; end")
A("                    a_neg1 <= a[7]; a_mag1 <= decode_mag(a);")
A("                    b_neg1 <= b[7]; b_mag1 <= decode_mag(b);")
A("                    state <= S_SUM;")
A("                end")
A("")
A("                // ~3 ns: 18-bit compare+add/subtract from FFs")
A("                S_SUM: begin")
A("                    sv2 <= sv1; sr2 <= sr1;")
A("                    if (a_neg1 == b_neg1) begin")
A("                        s_neg2 <= a_neg1;")
A("                        s_mag2 <= {1'b0, a_mag1} + {1'b0, b_mag1};")
A("                    end else if (a_mag1 >= b_mag1) begin")
A("                        s_neg2 <= a_neg1;")
A("                        s_mag2 <= {1'b0, a_mag1} - {1'b0, b_mag1};")
A("                    end else begin")
A("                        s_neg2 <= b_neg1;")
A("                        s_mag2 <= {1'b0, b_mag1} - {1'b0, a_mag1};")
A("                    end")
A("                    state <= S_PREHASH;")
A("                end")
A("")
A("                // ~2.5 ns: parallel OR trees + precomputed result bytes")
A("                // All computed in parallel from s_mag2 (single FF source):")
A("                //   any3[k] = |s_mag2[17:k]  (OR tree per bit position)")
A("                //   rbyte3[k] = precomputed {eb,ba} for shift k")
A("                S_PREHASH: begin")
A("                    sv3 <= sv2; sr3 <= sr2; s_neg3 <= s_neg2; s_mag3 <= s_mag2;")
A("                    is_z3  <= (s_mag2 == 19'd0);")
A("                    is_ov3 <= (s_mag2 > 19'd229376);")
A("                    is_dn3 <= (s_mag2 != 19'd0) && (s_mag2 < 19'd8);")
A("                    // Prefix-OR: any3[k] = |s_mag2[17:k]")
A("                    // Synthesized as parallel OR trees from s_mag2 FF bits")

for k in range(18):
    if k == 17:
        A("                    any3[%d] <= s_mag2[17];" % k)
    else:
        A("                    any3[%d] <= |s_mag2[17:%d];" % (k, k))

A("                    // Precomputed result bytes for each shift k=0..14")
A("                    // eb_k = k+2 (constant), ba_k = s_mag2[k+3:k] + rounding")
for k in range(15):
    eb_k = k + 2
    eb_kp1 = k + 3
    # ba_base = s_mag2[k+3:k] (4 bits, wiring)
    # dr = do_round_expr(k)
    # carry = oor & dr = (ba_base == 4'hF) & dr
    # ba_f = carry ? 4'd8 : (ba_base + dr)[3:0]
    # eb_f = carry ? (k+3) : (k+2)  -- both constants
    # clamped: (eb_f==15 && ba_f[2:0]==3'd7) i.e. result would be 0x7E
    #   carry=1, eb_kp1=15 -> k=12: eb_kp1=15, check ba_f=4'd8 -> ba[2:0]=0 -> not clamped
    #   carry=0, eb_k=15   -> k=13: possible if ba[2:0]==7
    #   carry=1, eb_kp1=16 -> k=13: overflow, clamp
    #   carry=0, eb_k=16   -> k=14: overflow, clamp (but caught by is_ov)
    dr = do_round_expr(k)
    A("                    begin : ph_k%d" % k)
    A("                        reg dr_%d; reg [3:0] ba_b_%d; reg carry_%d;" % (k, k, k))
    A("                        reg [3:0] ba_f_%d; reg [3:0] eb_f_%d;" % (k, k))
    A("                        reg clamped_%d;" % k)
    A("                        dr_%d    = %s;" % (k, dr))
    A("                        ba_b_%d  = s_mag2[%d:%d];" % (k, k+3, k))
    A("                        carry_%d = dr_%d & (ba_b_%d == 4'hF);" % (k, k, k))
    A("                        ba_f_%d  = carry_%d ? 4'd8 : (ba_b_%d + {3'd0, dr_%d});" % (k, k, k, k))
    A("                        eb_f_%d  = carry_%d ? 4'd%d : 4'd%d;" % (k, k, eb_kp1, eb_k))
    # Clamp conditions:
    # If eb_f > 15: always clamp (only possible if carry and k=13: eb=16 -> clamp)
    # If eb_f == 15 and ba_f[2:0] == 7: clamp (NaN slot, but FP8 E4M3 has no inf, uses these as valid)
    # Actually for FP8 E4M3: max is 0x7E (eb=14, ba=6), 0x7F is NaN.
    # So eb=15 with ba[2:0]=7 (ba_f=15): that's NaN encoding, should clamp to 7E
    # eb=15 with ba[2:0]<7: valid numbers (e.g. 0x78=448)
    A("                        clamped_%d = (eb_f_%d > 4'd15) |" % (k, k))
    A("                                    ((eb_f_%d == 4'd15) & (ba_f_%d[2:0] == 3'd7));" % (k, k))
    A("                        rbyte3[%d]  <= clamped_%d ? 7'h7E : {eb_f_%d[3:0], ba_f_%d[2:0]};" % (k, k, k, k))
    A("                        rclamp3[%d] <= clamped_%d;" % (k, k))
    A("                    end")

A("                    state <= S_LOG;")
A("                end")
A("")
A("                // ~1.5 ns: log2 from prefix-OR FFs + one-hot sh encoding")
A("                // any3[k] FFs -> lead[k] = any3[k] & ~any3[k+1] (1 AND gate per bit)")
A("                // log2 from lead[] -> binary encode (2-3 LUT levels from FFs)")
A("                // sh = log2-3: one-hot encode into sh_oh4[0..14]")
A("                S_LOG: begin")
A("                    sv4 <= sv3; sr4 <= sr3; s_neg4 <= s_neg3; s_mag4 <= s_mag3;")
A("                    is_z4 <= is_z3; is_ov4 <= is_ov3; is_dn4 <= is_dn3;")
A("                    begin : log_block")
A("                        reg [4:0] lg;")
A("                        reg [4:0] sh;")
A("                        // Priority encode from any3 FFs:")
A("                        // log2 = highest k where any3[k]=1")
A("                        // (any3 is thermometer: 1s from 0 to log2, 0s above)")
A("                        casez ({any3[17],any3[16],any3[15],any3[14],any3[13],")
A("                                any3[12],any3[11],any3[10],any3[9], any3[8],")
A("                                any3[7], any3[6], any3[5], any3[4], any3[3],")
A("                                any3[2], any3[1], any3[0]})")
A("                            18'b1?????????????????: lg = 5'd17;")
A("                            18'b01????????????????: lg = 5'd16;")
A("                            18'b001???????????????: lg = 5'd15;")
A("                            18'b0001??????????????: lg = 5'd14;")
A("                            18'b00001?????????????: lg = 5'd13;")
A("                            18'b000001????????????: lg = 5'd12;")
A("                            18'b0000001???????????: lg = 5'd11;")
A("                            18'b00000001??????????: lg = 5'd10;")
A("                            18'b000000001?????????: lg = 5'd9;")
A("                            18'b0000000001????????: lg = 5'd8;")
A("                            18'b00000000001???????: lg = 5'd7;")
A("                            18'b000000000001??????: lg = 5'd6;")
A("                            18'b0000000000001?????: lg = 5'd5;")
A("                            18'b00000000000001????: lg = 5'd4;")
A("                            18'b000000000000001???: lg = 5'd3;")
A("                            18'b0000000000000001??: lg = 5'd2;")
A("                            18'b00000000000000001?: lg = 5'd1;")
A("                            default: lg = 5'd0;")
A("                        endcase")
A("                        sh = (lg >= 5'd3) ? lg - 5'd3 : 5'd0;")
A("                        // One-hot encode sh into sh_oh4")
A("                        sh_oh4 <= 15'd0;")
A("                        if (sh < 5'd15) sh_oh4[sh] <= 1'b1;")
A("                    end")
A("                    state <= S_ROUND;")
A("                end")
A("")
A("                // ~1.0 ns: AND-OR tree selects precomputed byte using one-hot sh_oh4")
A("                // Each sh_oh4[k] is a registered FF; each rbyte3[k] is a registered FF")
A("                // Result: OR of (rbyte3[k] & {7{sh_oh4[k]}}) for k=0..14")
A("                S_ROUND: begin")
A("                    sv5 <= sv4; sr5 <= sr4; s_neg5 <= s_neg4; s_mag5 <= s_mag4;")
A("                    is_z5 <= is_z4; is_ov5 <= is_ov4; is_dn5 <= is_dn4;")
A("                    begin : round_block")
A("                        reg [6:0] sel_byte;")
A("                        reg       sel_clamp;")
A("                        integer   _k;")
A("                        sel_byte  = 7'd0;")
A("                        sel_clamp = 1'b0;")
A("                        for (_k=0; _k<15; _k=_k+1) begin")
A("                            sel_byte  = sel_byte  | (rbyte3[_k] & {7{sh_oh4[_k]}});")
A("                            sel_clamp = sel_clamp | (rclamp3[_k] & sh_oh4[_k]);")
A("                        end")
A("                        rbyte5  <= sel_byte;")
A("                        rclamp5 <= sel_clamp;")
A("                    end")
A("                    state <= S_ENCODE;")
A("                end")
A("")
A("                // ~0.5 ns: sign combine + special-case override (all from FFs)")
A("                S_ENCODE: begin")
A("                    if (sv5)")
A("                        result <= sr5;")
A("                    else if (is_z5)")
A("                        result <= 8'h00;")
A("                    else if (is_ov5)")
A("                        result <= {s_neg5, 7'h7E};")
A("                    else if (is_dn5)")
A("                        result <= {s_neg5, 1'b0, 3'b000, s_mag5[2:0]};")
A("                    else if (rclamp5)")
A("                        result <= {s_neg5, 7'h7E};")
A("                    else")
A("                        result <= {s_neg5, rbyte5};")
A("                    done  <= 1'b1;")
A("                    busy  <= 1'b0;")
A("                    state <= S_IDLE;")
A("                end")
A("")
A("                default: state <= S_IDLE;")
A("            endcase")
A("        end")
A("    end")
A("")
A("endmodule")

verilog = "\n".join(L) + "\n"
out = r"c:\Users\Administrator\Desktop\Hackathon 2026\Our Fork\TechCrash2026\challenge_submissions\fp8_adder\fpga\src\fp8_adder.v"
with open(out, "w", encoding="utf-8") as f:
    f.write(verilog)
print("Written: %s (%d bytes, %d lines)" % (out, len(verilog), verilog.count('\n')))
